spring:
  application:
    name: book-reader-users-api
  profiles:
    active: development
  config:
    import: ${CONFIG_SERVER:optional:configserver:http://localhost:8080}
  cloud:
    config:
      fail-fast: true
server:
  port: 8081